### ISSUE TITLE
Adding skins with dash in them results in "invalid skin name"

### ISSUE THREAD

**Issue by Bastrabun** [minetest-mods/skinsdb#110]
To reproduce, do in a running server (needs https://gitea.your-land.de/your-land/yl_skinsdb_addon):

```
//lua local myname = "singleplayer" local path = mymod.worldpath .. "my_skins/textures/" local filename= "player.has-dash.0.png" local a,b = skins.register_skin(path, filename)  core.chat_send_player(myname, dump(a)..","..dump(b))
```

or in some mod during loadtime. 

Dashes are legal characters for naming, but also missing from the unittests.

Server version is 5.8.0, all other skins work nicely, even those with underscores.

In skinlist.lua line 9 the pattern 

```
	local prefix, sep, identifier, extension = filename:match("^(%a+)([_.])([%w_.]+)%.(%a+)$")
```

doesn't hit dashes. Maybe instead this?

```
	local prefix, sep, identifier, extension = filename:match("^(%a+)([_.])([%w_.-]+)%.(%a+)$")
```

Seems to work with the cases I tested, but not sure, whether really really suitable.

For my reference 7459

**Comment by SmallJoker** [comment]
b3e2186
