### ISSUE TITLE
GPLv3 and CC-BY-NC-SA are incompatible licenses.

### ISSUE THREAD

**Issue by rrigby** [minetest-mods/skinsdb#19]

**Comment by sofar** [comment]
`update_skins_db.sh` is the only problem. We should remove it.

**Comment by sofar** [comment]
@bell07 I agree this is an issue, and we should resolve it.

**Comment by SmallJoker** [comment]
Since almost nothing is left over from cornernote's original code it would also be possible to agree a license change of the project.

**Comment by bell07** [comment]
Created pull request that removes all updaters. The "Windows" Updater did provided Newtonsoft.Json.dll that is not free. The Python updater is broken for me.

But I ask for confirm / second-approve this PR before I merge it

**Comment by sofar** [comment]
> Which licenses are compatible to CC-BY-NC-SA?

shell scripts like this should just be ISC or MIT, only. There really is 
nothing special about them. GPL-3.0 if you're wild.

**Comment by bell07** [comment]
Now I read the license. To honor the license I need to say I modified the script in 0ed683210e526edcdb931e8c136f87473d2e2441 and 11c39cd149f0ebd5df599e2b7d8148d3306055ee. 
The current copy is "modified work".  Good or bad from license point of view?

**Comment by sofar** [comment]
bad, since, at that time, the -NC license applied to that file.

Best to write a simple new scraper. Even better to just temporarily delete the version right now to avoid further issues.

**Comment by bell07** [comment]
Updaters removed. New updaters requested in #21
