### ISSUE TITLE
Skins appear 50% below terrain on Minetest 5.0

### ISSUE THREAD

**Issue by za267** [minetest-mods/skinsdb#23]
This version of skinsdb appears to be incompatible with server 5.0.1.  Not sure about 5.0.0.  

The textures appear 50% below the player.

**Comment by b3u** [comment]
I still have this issue @za267 @bell07 
Created a new world of mtg with just skinsdb. Still happens

**Comment by bell07** [comment]
Do you use the latest GIT version? from 10 March?
Do you use the playeranim mod?

**Comment by b3u** [comment]
I think I use the latest git. I didn't use playeranim mod.
