### ISSUE TITLE
How to download skins using /bin/bash ?

### ISSUE THREAD

**Issue by zaoqi** [minetest-mods/skinsdb#38]

**Comment by SmallJoker** [comment]
The python/bash scripts were removed in 1697218

The replacement for the scripts is the chat command `/skinsdb_download_skins`
How to use: https://github.com/minetest-mods/skinsdb#installing-skins

**Comment by zaoqi** [comment]
Can this updater run without minetest?

**Comment by SmallJoker** [comment]
No, sadly it can't. You'd have to write your own updater script that does not depend on Minetest.
