### ISSUE TITLE
pre-generated preview shows as separate defunct skin

### ISSUE THREAD

**Issue by Bastrabun** [minetest-mods/skinsdb#44]
To reproduce, put a skin preview file into the textures folder, to force skinsdb to use this pre-generated preview instead of the generated one. It will show in the skin selection formspec as a separate skin. I added a skin and its pregenerated preview, also a screenshot of the error. 

I named the skins according to the readme. In my skins there's an additional underscore, but I also tried to replace it with a hyphen. In both cases the preview gets recognized as separate skin.

Windows 10, MT 5.1.0, minetest_game, the only mod activated is skinsdb, release = 2930

![character_farmer_m](https://user-images.githubusercontent.com/59294479/74216190-e266f580-4ca3-11ea-93b7-6948c1647205.png)
![character_farmer_m_preview](https://user-images.githubusercontent.com/59294479/74216192-e2ff8c00-4ca3-11ea-9e30-ed66bf9d434c.png)
![grafik](https://user-images.githubusercontent.com/59294479/74216298-3ffb4200-4ca4-11ea-88c8-1c6cc25b13b2.png)

**Comment by bell07** [comment]
Please check the file names. The preview files are still supported, but needs to be named "*_preview.png" (with underscore, lowercase).

**Comment by Bastrabun** [comment]
I noticed in the screenshot I have 3d_armor active. I tried without, the same error occurs. Here are my filenames:

character_farmer_m_preview.png
character_farmer_m.png

I thought it had something to do with the additional underscores between "farmer" and "m", but the same error occurs when I rename them to

character_farmer_preview.png
character_farmer.png

**Comment by bell07** [comment]
@Bastrabun, Can you pls. zip your skinsdb folder and upload them?

**Comment by Bastrabun** [comment]
Sure. Here it comes.
[skinsdb.zip](https://github.com/minetest-mods/skinsdb/files/4188666/skinsdb.zip)

**Comment by bell07** [comment]
Fixed. Thank you for reporting
