### ISSUE TITLE
I can't see my skin's arm in first person

### ISSUE THREAD

**Issue by pxsxs** [minetest-mods/skinsdb#45]
I can't see my skin's arm in first person

**Comment by SmallJoker** [comment]
Is the problem that you cannot see the arm, or that the arm texture doesn't use the skin colors?
Former is a client setting issue, latter a feature request.

**Comment by notavaliable** [comment]
The texture of the arm isn't the same as the skin. I thought maybe it was a compatibility problem.

**Comment by BruceMustache** [comment]
Would be good to have skin support arm texture

**Comment by BruceMustache** [comment]
Is possible skindb to change arm texture? That would be nice

**Comment by bell07** [comment]
Just for reference, implemented in player_api_modpack as separate mod: https://github.com/bell07/minetest-player_api_modpack/tree/master/newhand
For skinsdb maybe the beter solution is to ask jordan4ibanez to add skinsdb support in https://github.com/jordan4ibanez/newhand
The player_api_modpack version is based on this mod.

**Comment by bell07** [comment]
Done in #66

**Comment by bell07** [comment]
Merged in #66
