### ISSUE TITLE
Skins downloading only partly working

### ISSUE THREAD

**Issue by Lejo1** [minetest-mods/skinsdb#49]
I tried to download all skins so I did:
`/skinsdb_download_skins 1 56`

I got a lot of Errors these are just examples I get them a lot more often.
These are the three "types" of errors I get
`2020-06-04 14:40:43: ERROR[CurlFetch]: http://minetest.fensta.bplaced.net/api/v2/get.json.php?getlist&page=8&outformat=base64 not found (Timeout was reached) (response code 200)`

`2020-06-04 14:40:43: WARNING[Server]: Lua Skins Updater: Failed to download URL=http://minetest.fensta.bplaced.net/api/v2/get.json.php?getlist&page=8&outformat=base64`

`2020-06-04 14:40:58: ERROR[CurlFetch]: http://minetest.fensta.bplaced.net/skins/1/21.png not found (HTTP response code said error) (response code 503)`

After the world restarted I only had 20 pages and not all.

**Comment by SmallJoker** [comment]
Indeed, these errors be handled in the Lua script. It might make sense to increase your `curl_timeout = 5000` minetest.conf setting in case the skins database is overloaded.

Will look into this.

**Comment by SmallJoker** [comment]
There were a few timeout adjustments in recent Minetest versions (5.9.0-dev) in addition to changed skin database URL (the original went offline).

Assuming this is fixed. Please re-open or reply if the issue still occurs.
