### ISSUE TITLE
Can't download skins

### ISSUE THREAD

**Issue by nolt** [minetest-mods/skinsdb#73]
Downloading doesn't work at all :/
```
~/.minetest/mods/skinsdb/updater# python3 update_skins.py 
Downloading skins from minetest.fensta.bplaced.net ...
Request failed!
```

same in-game server crashes. Any ideas?

**Comment by SmallJoker** [comment]
@adrido Your website is dead.

**Comment by nolt** [comment]
I've checked today and skins are downloads while sites still says 404. But got another issue:

```
Added #2196 Name: Badi Author: L-A Azeddine License: CC BY-SA 3.0
Added #2197 Name: Badi 2 Author: L-A Azeddine License: CC BY-SA 3.0
Added #2198 Name: water Author: water License: CC BY-SA 3.0
Traceback (most recent call last):
  File "/root/.minetest/mods/skinsdb/updater/update_skins.py", line 26, in <module>
    raw_data = base64.b64decode(json["img"])
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

**Comment by SmallJoker** [comment]
I don't know if `update_skins.py` is still maintained and would instead recommend to use the Lua implementation which can be used by server owners: https://github.com/minetest-mods/skinsdb/blob/master/skins_updater.lua

**Comment by nolt** [comment]
Thanks for your anserw I used it already and it seems to work just fine - no errors occured.
