### ISSUE TITLE
only female textures have their gender postfixed? (default textures in branch contentdb)

### ISSUE THREAD

**Issue by nissaofthesea** [minetest-mods/skinsdb#77]
`character_castaway_female.png` is female, `character_castaway.png` is presumably male, and so on for rogue and farmer.
this may come across weird since it implies male as default (having no postfix).

i believe the following would be an improvement:
```text
renamed    meta/character_castaway.txt -> meta/character_castaway_male.txt
renamed    meta/character_farmer.txt -> meta/character_farmer_male.txt
renamed    meta/character_rogue.txt -> meta/character_rogue_male.txt
renamed    textures/character_castaway.png -> textures/character_castaway_male.png
renamed    textures/character_farmer.png -> textures/character_farmer_male.png
renamed    textures/character_rogue.png -> textures/character_rogue_male.png
```

and in the meta files:
```diff
@@ -1,3 +1,3 @@
-Castaway
+Castaway male
sirrobzeroone
CC0/Public Domain
```
and etc.

another option would be to name them and remove the postfix altogether (which i could also contribute).

i can send a pr, but i don't know (given that they are licensed) that it's as straightforward as renaming and keeping the same author/license.

**Comment by bell07** [comment]
I agree with the proposed change. Please set up an PR
