### ISSUE TITLE
The database doesn't support uploading 1.8 skins

### ISSUE THREAD

**Issue by binarydigitz01** [minetest-mods/skinsdb#85]
When I try to upload this perfectly valid skin: 
![character_good-bad](https://user-images.githubusercontent.com/47600778/231059597-f1da3332-a840-47ff-b909-fe0cd061ed22.png)
It doesn't accept it, saying it's not 64*32 reslolution. However ingame the skin works without using the database. Since I can't find contact information of the owner, I thought I would open this issue.

**Comment by SmallJoker** [comment]
This repository is not in charge for database uploads. Please report this issue either in the forum or its dedicated repository: https://forum.minetest.net/viewtopic.php?f=14&t=4497
