### ISSUE TITLE
SkinDB site no longer up, so py script won't work

### ISSUE THREAD

**Issue by CallMeDax** [minetest-mods/skinsdb#88]
### Problem:
The minetest SkinDB at minetest.fensta.bplaced.net is down, causing the script and download command to fail.
### Solution:
Remove the command and script as they don't function anymore.
### Alternatives:
Add a notice/warning that the site is down.
### Notes:
I am aware that the developers of this mod are not responsible for that database, but as it is used in the mod, players should be shown/told that it isn't working anymore.

**Comment by fluxionary** [comment]
what's the story on why it's down? it sounds like you expect it to be down permanently? is anyone willing to create and host a clone of the API?

**Comment by CallMeDax** [comment]
The original owner doesn't seem to be responding on the [forums](https://forum.minetest.net/viewtopic.php?f=14&t=4497&start=275)
Some were discussing on whether to create a new database but there hasn't been a definite answer of whether anyone will. Also the code in the report for the site is almost 10 years old, sounds like it would be more likely rewritten which would take a while.

Here is the [source code](https://bitbucket.org/kingarthursteam/mt-skin-db) if you want to take a look at it.

**Comment by SmallJoker** [comment]
This has already happened a few times in the past - perhaps once a year. I suppose the account was either inactive for too long or the traffic too high for this host. I now sent him an email, which he will hopefully see soon.
The source code does exist, but without any license. Hence it is not FLOSS.

**Comment by wsor4035** [comment]
its been down for a few months now. have a replacement api (original had no license and was rather outdated/trash code). working on a pr for skinsdb now
