### ISSUE TITLE
 private skin on local server doesn't work

### ISSUE THREAD

**Issue by mmmsued** [minetest-mods/skinsdb#96]
Private skin with "player_[playername]_[name or number].png" doesn't work on a local server. On a real server everything is fine.

Tried with minetest 5.8.0 on Windows 10.

**Comment by Niklp09** [comment]
Maybe https://github.com/minetest-mods/skinsdb/issues/54?

**Comment by mmmsued** [comment]
Solved. I am not sure, why it works now. Maybe cache problems ...
